from voidlinux/voidlinux

run xbps-install -Suyy
run xbps-install -Suyy
run xbps-install -Syy git make gcc pkg-config curl
run xbps-install -Syy libX11-devel libXft-devel libXinerama-devel freetype-devel

